name: Main Test

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]#[windows-latest, ubuntu-20.04, macOS-latest]
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install selenium
        python -m pip install webdriver-manager
        python -m pip install Faker
        python -m pip install pytest
        python -m pip install pytest-xdist
        python -m pip install pandas
    - name: Run main.py
      run: |
        python main.py
