name: Main Test

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-20.04, macOS-latest]
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install selenium
        python -m pip install webdriver-manager
        python -m pip install Faker
        python -m pip install pytest
        python -m pip install pytest-xdist
        python -m pip install pandas
        python -m pip install allure-pytest
    - name: Initialize allure report
      # You may pin to the exact commit or the version.
      # uses: afiore/action-allure-report@e43ebd6f4f4c74b07b1eb02f042902bbe6786a19
      uses: afiore/action-allure-report@v0.1.0
      with:
        # Allure test result data dir
        results-dir: allure-results/*
        # Allure report target dir
        report-dir: allure-report --clean
    - name: Run main.py
      run: |
        python main.py
    - name: Upload allure results to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results/
  
  allure-upload:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download allure-report from build
        uses: actions/download-artifact@v3
        with:
          name: allure-report
      - name: Initialize allure report
        # You may pin to the exact commit or the version.
        # uses: afiore/action-allure-report@e43ebd6f4f4c74b07b1eb02f042902bbe6786a19
        uses: afiore/action-allure-report@v0.1.0
        with:
          # Allure test result data dir
          results-dir: allure-results/*
          # Allure report target dir
          report-dir: allure-report --clean
      - name: Generate allure report
        run: |
          allure generate allure-results/* --clean
      - name: Upload allure report to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report/
        
