name: Testing Test Cases

on: 
  push:
    branches:
      - main
      - testing-test-cases

defaults:
  run:
    working-directory: ./test_cases/

jobs:
  build:
    runs-on: ubuntu-latest 
    name: Test Changed Test Cases
    steps:
      - uses: actions/checkout@v3  

      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            if [[ $changed_file == "test_cases/"* ]]; then
              echo "Do something with this ${changed_file}."
            fi
          done
