name: Testing Test Cases

on: 
  push:
    branches:
      - main
      - testing-test-cases

jobs:
  build:
    runs-on: ubuntu-latest 
    name: Test Changed Test Cases
    steps:
      - uses: actions/checkout@v3  

      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            echo "Do something with this ${changed_file}."
          done
