name: Testing Test Cases

on: 
  workflow_dispatch:
#   push:
#     branches:
#       - main

jobs:
  build:
    runs-on: ubuntu-latest 
    name: Test Changed Test Cases
    steps:
      - uses: actions/checkout@v3  
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files in the test_cases folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        #with:
         # files: |
          #  test_cases/**/*.py

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
