name: Testing Test Cases

on: 
  push:
    branches:
      - "**"

defaults:
  run:
    working-directory: ./test_cases/

jobs:
  build:
    runs-on: ubuntu-latest 
    name: Test Modified or Added Test Cases
    steps:
      - uses: actions/checkout@v3  
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install selenium
          python -m pip install Faker
          python -m pip install pytest
          python -m pip install pandas
          python -m pip install allure-pytest

      - name: Test Modified or Added Test Cases
        id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            if [[ $changed_file == "test_cases/"* ]]; then
              pytest ${changed_file} -s --production=false
            fi
          done
